# Отбор необходимых данных

In [4]:
import pandas as pd

## а) Сохраните в файл train_part.csv следующую часть из файла train.csv
### - Строки, где matches больше чем среднее

In [24]:
df = pd.read_csv('https://raw.githubusercontent.com/Serfentum/bf_course/master/14.pandas/train.csv')
df.query('matches > matches.mean()')

,pos,reads_all,matches,mismatches,deletions,insertions,A,C,T,G,A_fraction,T_fraction,G_fraction,C_fraction
1,280,8045,7995,48,19,9,NaN,16.0,13.0,19.0,NaN,0.001355,0.002392,0.001914
2,281,8045,7983,50,16,5,NaN,24.0,4.0,24.0,NaN,0.000639,0.002875,0.002310
3,282,8049,7510,505,33,65,105.0,11.0,395.0,NaN,0.012750,0.049096,NaN,0.000919
4,283,8042,7786,155,115,62,46.0,NaN,93.0,31.0,0.004960,0.010992,0.003186,NaN
5,284,8048,7094,104,864,241,24.0,57.0,26.0,NaN,0.002687,0.002429,NaN,0.006792
17,296,8039,4870,1883,1308,50,NaN,657.0,261.0,966.0,NaN,0.032170,0.119298,0.081841
19,298,8047,5939,769,1345,12,124.0,NaN,266.0,394.0,0.014754,0.032077,0.048882,NaN
20,299,8043,6284,728,1053,60,210.0,197.0,NaN,328.0,0.025404,NaN,0.039977,0.024082
21,300,8049,6722,862,468,64,81.0,142.0,644.0,NaN,0.010178,0.079181,NaN,0.017205
22,301,8050,6135,1395,516,51,100.0,483.0,825.0,NaN,0.011395,0.102406,NaN,0.059618
25,304,8051,5310,1492,1248,63,204.0,361.0,NaN,937.0,0.024770,NaN,0.115451,0.044953
26,305,8048,5360,1054,1641,36,91.0,265.0,714.0,NaN,0.010243,0.088662,NaN,0.032133
32,311,8051,5029,1479,1558,90,272.0,575.0,634.0,NaN,0.033311,0.078508,NaN,0.071593
33,312,8051,4745,1766,1556,159,294.0,308.0,NaN,1175.0,0.035579,NaN,0.145651,0.037627
34,313,8054,5037,1337,1687,66,329.0,274.0,733.0,NaN,0.040546,0.091010,NaN,0.033847
41,320,8052,6290,584,1194,18,125.0,NaN,215.0,250.0,0.015516,0.025557,0.030306,NaN
42,321,8059,6471,748,839,53,152.0,210.0,NaN,403.0,0.018040,NaN,0.049747,0.025020
43,322,8053,7298,451,315,243,141.0,170.0,151.0,NaN,0.017430,0.017598,NaN,0.020873
44,323,8054,6753,996,315,78,122.0,169.0,717.0,NaN,0.014191,0.088275,NaN,0.020234
45,324,8052,6893,667,508,49,103.0,301.0,272.0,NaN,0.011903,0.032569,NaN,0.037466
49,328,8059,4922,983,2163,197,256.0,608.0,123.0,NaN,0.031507,0.015213,NaN,0.074936
53,332,8057,5381,1619,1066,88,408.0,NaN,344.0,881.0,0.050222,0.041820,0.108997,NaN
54,333,8053,6251,949,868,25,170.0,519.0,NaN,277.0,0.020705,NaN,0.033372,0.063630
55,334,8057,6850,544,675,6,NaN,146.0,118.0,290.0,NaN,0.013547,0.035473,0.017937
56,335,8054,7341,259,459,26,49.0,NaN,63.0,161.0,0.005477,0.006980,0.019948,NaN
57,336,8061,7278,367,423,3,97.0,157.0,NaN,128.0,0.011010,NaN,0.015016,0.018778
58,337,8056,7542,471,58,7,NaN,63.0,47.0,367.0,NaN,0.004584,0.045444,0.007767
59,338,8061,7967,62,29,5,17.0,NaN,26.0,33.0,0.001060,0.002207,0.003992,NaN
60,339,8062,8002,48,14,3,14.0,14.0,33.0,NaN,0.001076,0.002953,NaN,0.001322
61,340,8061,7918,146,16,4,NaN,75.0,43.0,33.0,NaN,0.005307,0.002951,0.008808
62,341,8059,7869,192,2,4,NaN,134.0,37.0,17.0,NaN,0.004250,0.002243,0.016619

### - Колонки pos, reads_all, mismatches, deletions, insertions

In [25]:
df_selected = df.query('matches > matches.mean()').loc[: ,['pos', 'reads_all', 'mismatches', 'deletions', 'insertions']].set_index('pos')

In [26]:
df_selected

     reads_all  mismatches  deletions  insertions
pos
280       8045          48         19           9
281       8045          50         16           5
282       8049         505         33          65
283       8042         155        115          62
284       8048         104        864         241
296       8039        1883       1308          50
298       8047         769       1345          12
299       8043         728       1053          60
300       8049         862        468          64
301       8050        1395        516          51
304       8051        1492       1248          63
305       8048        1054       1641          36
311       8051        1479       1558          90
312       8051        1766       1556         159
313       8054        1337       1687          66
320       8052         584       1194          18
321       8059         748        839          53
322       8053         451        315         243
323       8054         996        315          78
324       8052         667        508          49
328       8059         983       2163         197
332       8057        1619       1066          88
333       8053         949        868          25
334       8057         544        675           6
335       8054         259        459          26
336       8061         367        423           3
337       8056         471         58           7
338       8061          62         29           5
339       8062          48         14           3
340       8061         146         16           4
341       8059         192          2           4